import { useEffect, useRef, useState } from 'react'
import { Link, NavLink, useLocation } from 'react-router-dom'
import { ArrowUpRight, Menu, X } from 'lucide-react'
const links = [['Services', '/services'], ['Work & demos', '/work'], ['Our approach', '/about'], ['Insights', '/blog']]
export default function Layout({ children }) {
  const [open, setOpen] = useState(false)
  const location = useLocation()
  const toggle = useRef(null)
  useEffect(() => { setOpen(false) }, [location.pathname])
  useEffect(() => { const close = (event) => { if (event.key === 'Escape' && open) { setOpen(false); toggle.current?.focus() } }; document.addEventListener('keydown', close); return () => document.removeEventListener('keydown', close) }, [open])
  return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><div className="container header-inner"><Link className="brand" to="/" aria-label="Vektar home"><img src="/android-chrome-192x192.png" width="40" height="40" alt="" /><span>vektar<span className="brand-dot">.</span></span></Link><nav className="desktop-nav" aria-label="Main navigation">{links.map(([label, path]) => <NavLink to={path} key={path}>{label}</NavLink>)}</nav><Link className="button button-small button-dark header-cta" to="/call">Talk to Vektar AI <ArrowUpRight size={16} /></Link><button ref={toggle} className="menu-toggle" type="button" aria-label={open ? 'Close navigation' : 'Open navigation'} aria-expanded={open} aria-controls="mobile-navigation" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div><nav id="mobile-navigation" className="mobile-nav" aria-label="Mobile navigation" hidden={!open}>{links.map(([label, path]) => <NavLink key={path} to={path}>{label}<ArrowUpRight size={18}/></NavLink>)}<Link to="/call">Talk to Vektar AI <ArrowUpRight size={18}/></Link></nav></header><main id="main" tabIndex={-1}>{children}</main><footer className="site-footer"><div className="container"><div className="footer-top"><Link className="brand footer-brand" to="/" aria-label="Vektar home"><img src="/android-chrome-192x192.png" width="42" height="42" alt="" /><span>vektar.</span></Link><p>Thoughtful engineering.<br/>Useful intelligence.</p><Link className="footer-cta" to="/call">Let’s talk about the work <ArrowUpRight size={22}/></Link></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Vektar</span><nav aria-label="Footer navigation"><Link to="/services">Services</Link><Link to="/about">About</Link><Link to="/blog">Insights</Link><Link to="/privacy">Privacy</Link></nav><span>Designed for what’s next.</span></div></div></footer></>
}
